[default]
address = "0.0.0.0"       # Endereço IP no qual a aplicação será executada
port = 8000                   # Porta padrão
workers = 8                 # Número de threads para requisições
log_level = "normal"              # Nível de log (normal, debug ou critical)
keep_alive = 5              # Tempo em segundos para conexões Keep-Alive
limits = { forms = "32 KiB" }  # Limite de tamanho para dados enviados via formulário
temp_dir = "/tmp"           # Diretório temporário para uploads
secret_key = "${ROCKET_SECRET_KEY}" # Chave secreta carregada de uma variável de ambiente

[debug]
log_level = "normal"

[release]
log_level = "critical"
